# Generated by Django 5.1.1 on 2024-09-16 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('subtitle_file', models.FileField(upload_to='subtitles/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_processing_subtitles', to='video_upload.video')),
            ],
        ),
    ]
